### ISSUE TITLE
Conversion Keras model to NNET: bug in writeNNet?

### ISSUE THREAD

**Issue by nathanael-fijalkow** [sisl/NNet#2]
I'm trying to convert a .model file created using Keras into .nnet.
I used keras2nnet.py with my own .model file, and I get the following error:

Traceback (most recent call last):
  File "keras2nnet.py", line 33, in <module>
    writeNNet(weights,biases,inputMins,inputMaxes,means,ranges,nnetFile)
  File "/home/nathanael/NNet/utils/writeNNet.py", line 76, in writeNNet
    f2.write("%.5e," % w[i][j]) #Five digits written. More can be used, but that requires more more space.
TypeError: only size-1 arrays can be converted to Python scalars

Thanks for your help!

**Comment by nathanael-fijalkow** [comment]
I understand: I am using networks with convolutions and max pooling, which are not supported by the converter (and by the .nnet format?). I'll close this issue then.
